---
title: "疎構造学習による異常検知"
output: html_document
---

# 10. 疎構造学習による異常検知

## 10.1 変数間の関係に基づく異常の判定: 基本的な考え方

依存関係のあるデータの例

```{r}
install.packages("UsingR")
library(UsingR) # パッケージの読み込み
plot(kid.weights[1:3]) # 子供の月齢・体重・身長の散布図
```

## 10.5 疎構造学習に基づく異常度の計算

### 10.5.1 外れ値解析の場合

```{r}
library("MASS")
data(Boston)
X <- as.matrix(Boston) # ボストンの各地区の住宅価格のデータを行列に読込
mx <- colMeans(X) # 標本平均
Xc <- X - matrix(1, nrow(X), 1) %*% mx # 中心化したデータ行列
s <- var(Xc) # 共分散行列の算出
glasso_out<-glasso(s, rho=.1) # グラフィカルラッソの実行
ramda <- glasso_out$wi # 精度行列の取得
ramda
```

```{r}
# 異常度の計算
calc_anomaly_outlier <- function(Xc, ramda) {
  colsize <- length(Xc[1,])
  rowsize <- length(Xc[,1])
  r_diag <- diag(ramda) # 精度行列の対角成分のベクトル
  a <- data.frame(matrix(ncol=colsize, nrow=rowsize))
  for(i in 1:rowsize) {
    v <- c(0, length=colsize)
    for(j in 1:colsize) {
      v[j] <- sum(ramda[j,] * Xc[i,])
    }
    a[i,] <- (log(2 * pi / r_diag) / 2) + (v^2 / (2 * r_diag))
  }
  a
}
```

```{r}
a <- calc_anomaly_outlier(Xc, ramda) # 異常度の計算
plot(a$X2, xlab="index", ylab="anomaly score") # 変数ごと
```

```{r}
a_of_1 <- t(as.matrix(a[1,]))
plot(a_of_1, xlab="variables", ylab="anomaly score") # サンプルごと
```

### 10.5.2 異常解析の場合

```{r}
# トレーニングと対象データに分割
data_split <- floor(nrow(Boston) / 2)
Xtr <- Boston[(1:data_split),]
X <- Boston[((data_split+1):nrow(Boston)),]

# トレーニングデータのグラフィカルラッソ
corTr <- cor(Xtr)
glasso_out_tr <- glasso(corTr, rho=.1) # グラフィカルラッソの実行
ramdaTr <- glasso_out_tr$wi # 精度行列の取得

# 対象データのグラフィカルラッソ
cor <- cor(X)
glasso_out <- glasso(cor, rho=.1) # グラフィカルラッソの実行
ramda <- glasso_out$wi # 精度行列の取得
```



```{r}
r_diag_tr <- diag(ramdaTr)
r_diag <- diag(ramda)
a <- (log(r_diag_tr/r_diag) / 2)
     - (
        (diag(ramdaTr %*% corTr %*% ramdaTr) / r_diag_tr)
        - (diag(ramda %*% corTr %*% ramda) / r_diag)
       ) / 2
plot(a)
```


