---
title: "データの演算と固有値、基本統計量"
output: html_document
---

# 3. データの演算と固有値、基本統計量

## 3.1. データの演算

### 算術演算 p31

```{r}
x <- c(1,2,3,4)
y <- c(4,2,3,1)
x + y
```

```{r}
x * y
```

```{r}
x / y
```

```{r}
x ^ 2
```

### 比較演算 p32

```{r}
x > y
```

### 論理演算 p33

```{r}
Lx <- c(T,T,F,F)
Ly <- c(T,F,F,T)
Lx & Ly
```

```{r}
Lx && Ly
```

### 行列の演算 p33

```{r}
A <- matrix(c(1,2,1,4),2,2)
D <- matrix(c(4,2,3,4,2,1),2,3)
A %*% D
```


### 対角行列と逆行列 p34

```{r}
diag(c(6,7,3))
```

```{r}
solve(A)
```

```{r}
A %*% solve(A)
```

## 3.2. 固有値と特異値の分解

### 固有値

```{r}
eigen(A)
```

```{r}
A.eig <- eigen(A)
A.eig$values
```

```{r}
A.eig$vectors
```

```{r}
A %*% A.eig$vectors
```

```{r}
A.eig$vectors %*% diag(A.eig$values)
```

### 特異値分解 p36

```{r}
(D.s <- svd(D))
```

```{r}
D.s$u %*% diag(D.s$d) %*% t(D.s$v)
```

## 3.3. 基本統計量

```{r}
(temp <- 1:10)
```

```{r}
sum(temp)
```

```{r}
summary(temp)
```

```{r}
apply(iris[,1:4],2,mean) # 列の平均
```

```{r}
apply(iris[,1:4],2,var) # 列の分散
```

```{r}
cov(iris[,-5])
```

```{r}
var(iris[,-5])
```


```{r}
cor(iris[,-5])
```



